<?php
#auto-generated by Gluon\Libraries\Cache::__construct on 01/27/2017 12:46:33 America/Los_Angeles
$return = array('admin.html.php'=>'<html>
    <head>
        <title>[#page.title#]</title>
<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />
<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">
<meta name=\"viewport\" content=\"width=device-width\">
<meta name=\"robots\" content=\"NOINDEX,NOFOLLOW\" />
<!-- Admin-->
<link rel=\"stylesheet\" href=\"/Gluon/cms/scripts/css/src/View/admin/_/css/style.css\"/>
<link rel=\"stylesheet\" href=\"/Gluon/cms/scripts/css/_/components/jquery/css/jquery-ui.structure.min.css\"/>
        <style>
            @font-face {
            font-family: \'gluon\';
            src: url(\'/Gluon/cms/_/fonts/Gluon.ttf\') format(\'truetype\');
            font-weight: normal;
            font-style: normal;
        }
        </style>
    </head>
    <body class=\"admin\">
        <div class=\"container\">
            <nav class=\"hide\">
                <div class=\"menu_header\">
                    <div class=\"button nav\">
                        <div class=\"arrow\"></div>
                    </div>
                </div>
                <ul>
                    <li><a href=\"admin\">Admin <span>A</span></a></li>
                    <li><a href=\"updates\">Updates <span>B</span></a></li>
                    <li><a href=\"pages\">Pages  <span>C</span></a></li>
                    <li><a href=\"plugins\">Plugins  <span>D</span></a></li>
                    <li><a href=\"themes\">Themes  <span>E</span></a></li>
                </ul>
            </nav>
            <header>
                <div class=\"left\">
                    <img src=\"/Gluon/cms/_/svg/logo.svg\" class=\"logo\" />
                    Gluon Content Management System
                </div>
                <div class=\"right\">
                    Welcome Jeremy
                </div>
            </header>
            <div class=\"body\">
                <section class=\"activity\">
                    <h2>
                        Activity
                    </h2>
                    <div class=\"clear\">
                        <div class=\"title\">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. sit amet, consectetur adipiscing elit. 
                        </div>
                        <div class=\"status\">
                            DELETED
                        </div>
                        <div class=\"date\">
                            Jan 25, 2017 5:31:23 
                        </div>
                    </div>
                    <div class=\"clear\">
                        <div class=\"title\">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.   
                        </div>
                        <div class=\"status\">
                            UPDATED
                        </div>
                        <div class=\"date\">
                            Jan 25, 2017 5:31:23 
                        </div>
                    </div>
                    <div class=\"clear\">
                        <div class=\"title\">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.   
                        </div>
                        <div class=\"status\">
                            UPDATED
                        </div>
                        <div class=\"date\">
                            Jan 25, 2017 5:31:23 
                        </div>
                    </div>
                    <div class=\"clear\">
                        <div class=\"title\">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. sit amet, consectetur adipiscing elit. 
                        </div>
                        <div class=\"status\">
                            UPLOADED
                        </div>
                        <div class=\"date\">
                            Jan 25, 2017 5:31:23 
                        </div>
                    </div>
                    <div class=\"clear\">
                        <div class=\"title\">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.   
                        </div>
                        <div class=\"status\">
                            UPDATED
                        </div>
                        <div class=\"date\">
                            Jan 25, 2017 5:31:23 
                        </div>
                    </div>
                    <div class=\"clear\">
                        <div class=\"title\">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. sit amet, consectetur adipiscing elit. 
                        </div>
                        <div class=\"status\">
                            UPLOADED
                        </div>
                        <div class=\"date\">
                            Jan 25, 2017 5:31:23 
                        </div>
                    </div>
                    <div class=\"clear\">
                        <div class=\"title\">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.   
                        </div>
                        <div class=\"status\">
                            UPDATED
                        </div>
                        <div class=\"date\">
                            Jan 25, 2017 5:31:23 
                        </div>
                    </div>
                    <div class=\"clear\">
                        <div class=\"title\">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. sit amet, consectetur adipiscing elit. 
                        </div>
                        <div class=\"status\">
                            UPLOADED
                        </div>
                        <div class=\"date\">
                            Jan 25, 2017 5:31:23 
                        </div>
                    </div>
                    <div class=\"clear\">
                        <div class=\"title\">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. sit amet, consectetur adipiscing elit. 
                        </div>
                        <div class=\"status\">
                            UPLOADED
                        </div>
                        <div class=\"date\">
                            Jan 25, 2017 5:31:23 
                        </div>
                    </div>
                    <div class=\"clear\">
                        <div class=\"title\">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. sit amet, consectetur adipiscing elit. 
                        </div>
                        <div class=\"status\">
                            UPLOADED
                        </div>
                        <div class=\"date\">
                            Jan 25, 2017 5:31:23 
                        </div>
                    </div>
                    <div class=\"clear\">
                        <div class=\"title\">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. sit amet, consectetur adipiscing elit. 
                        </div>
                        <div class=\"status\">
                            UPLOADED
                        </div>
                        <div class=\"date\">
                            Jan 25, 2017 5:31:23 
                        </div>
                    </div>
                    <div class=\"clear\">
                        <div class=\"title\">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. sit amet, consectetur adipiscing elit. 
                        </div>
                        <div class=\"status\">
                            UPLOADED
                        </div>
                        <div class=\"date\">
                            Jan 25, 2017 5:31:23 
                        </div>
                    </div>
                </section>
                <section class=\"analytics\">
                    <h2>
                        Analytics
                    </h2>  
                </section>
            </div>
            <aside class=\"hide\">
                <div class=\"menu_header\">
                    <div class=\"button aside\">
                        <div class=\"\"></div>   
                    </div>
                </div>
                <div class=\"menu_header\">
                    <div class=\"button\">
                        <div class=\"dwn_arrow\"></div>   
                    </div>
                </div>
            </aside>
            <footer>
                Copyright &copy; 2017 All Rights Reserved 
            </footer>
        </div>
        <!-- Admin-->
<script src=\"/Gluon/cms/scripts/js/_/components/jquery/jquery-3.1.1.min.js\"></script>
<script src=\"/Gluon/cms/scripts/js/src/View/admin/_/components/js/_admin.js\"></script>
<script src=\"/Gluon/cms/scripts/js/src/View/admin/_/components/js/_ajax.js\"></script>
<script src=\"/Gluon/cms/scripts/js/src/View/admin/_/components/js/_install.js\"></script>
<script src=\"/Gluon/cms/scripts/js/src/View/admin/_/components/js/script.js\"></script>
<script src=\"/Gluon/cms/scripts/js/_/components/jquery/jquery-ui.min.js\"></script>
    </body>
</html>','install.html.php'=>'<html>
    <head>
        <title>[#page.title#]</title>
<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />
<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">
<meta name=\"viewport\" content=\"width=device-width\">
<meta name=\"robots\" content=\"NOINDEX,NOFOLLOW\" />
<!-- Admin-->
<link rel=\"stylesheet\" href=\"/Gluon/cms/src/View/admin/_/css/style.css\"/>
<link rel=\"stylesheet\" href=\"/Gluon/cms/_/components/jquery/css/jquery-ui.structure.min.css\"/>
    </head>
    <body class=\"install\">
        <div class=\"container\">
            <div class=\"box\">
                <img src=\"/Gluon/cms/_/svg/logo.svg\" class=\"logo\" />
                <div class=\"step stepone\">
                    <h1>
                        Welcome!
                    </h1>
                    to the
                    <h2>Gluon Content Management System</h2>
                    <button class=\"startb\">Get Started</button>
                </div>
                <div class=\"step one\">
                    <h2>
                        Let\'s setup your login
                    </h2>
                    <div class=\"hidden required\">* required</div>
                    <input type=\"text\" data-name=\"friendlyname\" class=\"required\" placeholder=\"YOUR NAME\" />
                    <br />
                    <div class=\"hidden required\">* required</div>
                    <input type=\"text\" data-name=\"username\" class=\"required\" placeholder=\"USER NAME\" />
                    <br />
                    <div class=\"hidden required\">* required</div>
                    <input type=\"text\" data-name=\"email\" class=\"required\" placeholder=\"EMAIL\" />
                    <br />
                    <div class=\"hidden required\">* required</div>
                    <input type=\"password\" data-name=\"password\" class=\"required\" placeholder=\"PASSWORD\" />
                    <br />
                    <button class=\"next-step\">Next Step --></button>
                </div>
                <div class=\"step two\">
                    <h2>
                        Database Connection
                    </h2>
                    <div class=\"hidden required\">* required</div>
                    <input type=\"text\" data-name=\"dbhost\" class=\"required\" placeholder=\"HOST\" />
                    <br />
                    <div class=\"hidden required\">* required</div>
                    <input type=\"text\" data-name=\"dbname\" class=\"required\" placeholder=\"DATABASE\" />
                    <br />
                    <div class=\"hidden required\">* required</div>
                    <input type=\"text\" data-name=\"dbusername\" class=\"required\" placeholder=\"USER NAME\"/>
                    <br />
                    <div class=\"hidden required\">* required</div>
                    <input type=\"password\" data-name=\"dbpassword\" class=\"required\" placeholder=\"PASSWORD\" />
                    <br />
                    <button class=\"prev-step\"><-- Prev Step</button>
                    <button class=\"next-step\">Next Step --></button>
                </div>
                <div class=\"step three\">
                    <h2>
                        FTP Connection
                    </h2>
                    <div class=\"hidden required\">* required</div>
                    <input type=\"text\" data-name=\"ftphost\" class=\"required\" placeholder=\"HOST\" />
                    <br />
                    <input type=\"text\" data-name=\"ftpport\" class=\"ftpport\" placeholder=\"PORT\" />
                    <select data-name=\"ftpprotocol\" class=\"ftpprotocol\">
                        <option value=\"ftp\">FTP - File Transfer Protocol</option>
                        <option value=\"sftp\">SFTP - SSH File Transfer Protocol</option>
                    </select>
                    <br />
                    <div class=\"hidden required\">* required</div>
                    <input type=\"text\" data-name=\"ftpusername\" class=\"required\" placeholder=\"USER NAME\"/>
                    <br />
                    <div class=\"hidden required\">* required</div>
                    <input type=\"password\" data-name=\"ftppassword\" class=\"required\" placeholder=\"PASSWORD\" />
                    <br />
                    <input type=\"checkbox\" data-name=\"ftpskip\" class=\"fltleft ftpskip\"/> <div class=\"ftpskip\">Do not install FTP at this time</div>
                    <br />
                    <button class=\"prev-step\"><-- Prev Step</button>
                    <button class=\"run-install\">Install</button>
                </div>
                <div class=\"running\">
                    <h2>
                        Please wait...
                    </h2>
                    <div class=\"install-pro\"></div>
                    <button class=\"prev-step hidden\"><-- Prev Step</button>
                </div>
            </div>
        </div>
        <!-- Admin-->
<script src=\"/Gluon/cms/_/components/jquery/jquery-3.1.1.min.js\"></script>
<script src=\"/Gluon/cms/src/View/admin/_/components/js/_admin.js\"></script>
<script src=\"/Gluon/cms/src/View/admin/_/components/js/_ajax.js\"></script>
<script src=\"/Gluon/cms/src/View/admin/_/components/js/_install.js\"></script>
<script src=\"/Gluon/cms/src/View/admin/_/components/js/script.js\"></script>
<script src=\"/Gluon/cms/_/components/jquery/jquery-ui.min.js\"></script>
    </body>
</html>',);