<?php
#auto-generated by Libraries\gl_Cache::__construct on 01/18/2017 22:50:22 America/Los_Angeles
$return = array('error_handler'=>'gl_ErrorHandler','media'=>array('upload_folder'=>'upload','allowed_mimetypes'=>array('1'=>'image/jpeg','2'=>'image/png','3'=>'image/pjpeg','4'=>'application/pdf',),),);