<?php
#auto-generated by Libraries\gl_Cache::__construct on 01/19/2017 16:48:33 America/Los_Angeles
$return = array('error_handler'=>'gl_ErrorHandler','jquery'=>'_/components/jquery/jquery-3.1.1.min.js','debugmode'=>'1','media'=>array('upload_folder'=>'upload','allowed_mimetypes'=>array('1'=>'image/jpeg','2'=>'image/png','3'=>'image/pjpeg','4'=>'application/pdf',),),);