<?php
#auto-generated by Gluon\Libraries\Cache::__construct on 01/27/2017 23:45:40 America/Los_Angeles
$return = array('error_handler'=>'ErrorHandler','jquery'=>'_/components/jquery/jquery-3.1.1.min.js','debugmode'=>'1','media'=>array('upload_folder'=>'upload','allowed_mimetypes'=>array('1'=>'image/jpeg','2'=>'image/png','3'=>'image/pjpeg','4'=>'application/pdf',),),);