<?php
#auto-generated by Gluon\Libraries\Cache::__construct on 01/22/2017 21:53:14 America/Los_Angeles
$return = array('class'=>'pdoDatabase','param'=>array('dsn'=>'mysql:dbname=database;host=localhost','username'=>'root','password'=>'password','encoding'=>'utf8','attributes'=>array('DEFAULT_TABLE_TYPE'=>'INNODB','DEFAULT_TABLE_CHARSET'=>'utf8','DEFAULT_TABLE_COLLATE'=>'utf8_general_ci',),),);