<?php
#auto-generated by Libraries\gl_Cache::__construct on 01/20/2017 12:04:13 America/Los_Angeles
$return = array('class'=>'gl_pdoDatabase','param'=>array('dsn'=>'mysql:dbname=database;host=localhost','username'=>'root','password'=>'password','encoding'=>'utf8','attributes'=>array('DEFAULT_TABLE_TYPE'=>'INNODB','DEFAULT_TABLE_CHARSET'=>'utf8','DEFAULT_TABLE_COLLATE'=>'utf8_general_ci',),),);