<?php
#auto-generated by Gluon\Libraries\Cache::__construct on 01/27/2017 12:46:33 America/Los_Angeles
$return = array('class'=>'pdoDatabase','param'=>array('dsn'=>'mysql:host=localhost;dbname=gl_db','username'=>'gl_db','password'=>'abc1234','encoding'=>'utf8','attributes'=>array('DEFAULT_TABLE_TYPE'=>'INNODB','DEFAULT_TABLE_CHARSET'=>'utf8','DEFAULT_TABLE_COLLATE'=>'utf8_general_ci',),),);