<?php
#auto-generated by Libraries\gl_Cache::__construct on 01/20/2017 12:04:13 America/Los_Angeles
$return = array('notice'=>array('verbose'=>array('added'=>'[#0#] : [#1#] added successfully',),'success'=>array('uploaded'=>'[#0#] was saved successfully.',),'theme_skipped'=>array('name'=>'Theme [#0#] [name] not set
Theme skipped
','type'=>'Theme [#0#] [type] not set
Theme skipped
','version'=>'Theme [#0#] version: [#1#] not compatible with current version: [#2#] --- Theme skipped
',),),'error'=>array('upload'=>array('sizemax'=>'This file [#0#] has exceeded the allowed size limit. [#1#]','notallowed'=>'This file [#0#] type is not allowed. [#1#]','movefile'=>'Failed to move file','upload'=>'File failed to upload','malicious'=>'File contains potential malicious content',),),);