<?php
#auto-generated by Libraries\gl_Cache::__construct on 01/14/2017 15:19:11 America/Los_Angeles
return array('default'=>array('path'=>'/var/www/html/dev/Gluon/cms/themes/default/default.info.yml','info'=>array('name'=>'Default','description'=>'The basic theme','author'=>'Jeremy Heminger','core'=>'1.x',),),);