<?php
namespace Gluon\Libraries;
/**
 *  
 *  Cache
 *  @author By Jeremy Heminger <j.heminger@061375.com>
 *  @copyright © 2016 
 *
 * */
use Symfony\Component\Yaml\Yaml;
use Gluon\Libraries\General;

class Cache
{
    
    // ---
    
    private $files;
    
    // ---
    
    private $header;
    
	// ---
	
	private $cache_error;
	
	// ---
	
	private $config_error;
    
	/**
	 * @param object $error_handler
	 * @return void
	 * */
    function __construct($error_handler)
	{
		$this->errors = $error_handler;
        $this->header  = "<?php\n#auto-generated by ".__METHOD__." on ".date('m/d/Y H:i:s e',strtotime('now'))."\n";
		$this->cache_error = " an error was thrown when attempting to create the cache. Make sure permissions are set to user:user 777 on folders: uploads/cache and cms/cache";
		$this->config_error = " an error was thrown when attempting to create or update a configuration file. Make sure permissions are set to user:user 777 on folder: ";
	}
    /**
     * empty the cache folder
     * @return void
     * */
    public function delete_cache()
    {
        // empty the cache folder
        foreach (new \DirectoryIterator('cache') as $fileInfo) {
            if(!$fileInfo->isDot()) {
                unlink($fileInfo->getPathname());
            }
        }
    }
    /**
     * recurse through specified folder search for specified file type
     * @param string $dir
     * @param string $ext
     * @param mixed $return the first time throughthis array needs to assigned
     * @return array
     * */
    public function recurse_get_files($dir,$ext = '.php',$return = false)
    {
        if(false === $return)
            $return = array();
        $Directory = new \RecursiveDirectoryIterator($dir);
        $Iterator = new \RecursiveIteratorIterator($Directory);
        $objects = new \RegexIterator($Iterator, '/^.+\\'.$ext.'$/i', \RecursiveRegexIterator::GET_MATCH);
        foreach($objects as $name => $object){
            $return[str_replace('.html.php','',basename($name))] = $name;
        }
        return $return;
    }
    /**
     * create the classes cache file ( a PHP array )
     * @param array $src the array to be converted to readable code
     * @param string $path the path to export to
     * @return bool
     * */
    public function put_classes($src,$path)
    {
		
        if(false == file_exists($path)) {
            $error[__LINE__.' '.$path] = @file_put_contents($path,$this->header);
            $error[__LINE__.' '.$path] = @file_put_contents($path,'$return = array(',FILE_APPEND);
        }
        $out = '';
        foreach($src as $s) {
            $out .= "'".$s."',";
        }
        $error[__LINE__.' '.$path] = @file_put_contents($path,$out,FILE_APPEND);
        if(in_array(false,$error)){
            $this->errors->set_error_message(__METHOD__.$this->cache_error);
            return false;
        }
        return true;
    }
    /**
	 * gathers the themes and places them into a single array to be placed in a file
     * @return bool
     * */
    public function themes()
    {
        $v = json_decode(file_get_contents(getcwd().'/v/.version'));
        $v = $v->version;
        $yml = array();
        $ymls = $this->recurse_get_files(getcwd().'/themes','.info.yml');
        $ymls = $this->recurse_get_files(getcwd().'/src/View/','.info.yml',$ymls);
        foreach($ymls as $f) {
            $name = str_replace('.info.yml','',basename($f));
            $app = Yaml::parse(file_get_contents($f));
            $tname = General::is_set($app,'name',false);
            if(false === $tname) {
                print General::message('notice',array('notice','theme_skipped','name'),array($name));
                continue;
            }
            $type = General::is_set($app,'type',false);
            if(false === $type) {
                print General::message('notice',array('notice','theme_skipped','type'),array($app['name']));
                continue;
            }
            $yml[$type][$name]['path'] = $f;
            $cv = str_replace(substr($v,strpos($v,'.'),strlen($v)),'',$v);
            $tcv = str_replace('.x','',$app['core']);
            if($cv > $tcv){
                unset($yml[$type][$name]);
                print General::message('notice',array('notice','theme_skipped','version'),array($app['name'],$tcv,$cv));
            }else{
                $yml[$type][$name]['info'] = $app;
            }
        }
        if(false === $this->add_config($yml,'cache/themes.yml.php')) {
            return false;
        }
        // else
	if(defined('VERBOSE'))print General::message('notice',array('notice','verbose','added'),array(__METHOD__,'cache/themes.yml.php'));
            return true;
    }
    /**
     * create a generic cache file ( a PHP array )
     * @param array $src the array to be converted to readable code
     * @param string $path the path to export to
     * @return bool
     * */
    public function add_config($src,$path) {
	
	
        $error[__LINE__.' '.$path] = @file_put_contents($path,$this->header);
        $error[__LINE__.' '.$path] = @file_put_contents($path,'$return = array(',FILE_APPEND);
	
        $out = $this->recurse_built_array($src);
	
        $error[__LINE__.' '.$path] = @file_put_contents($path,$out,FILE_APPEND);
	
        $this->add_tail($path);
	
        if(in_array(false,$error)){
            $this->errors->set_error_message(__METHOD__.$this->cache_error);
			foreach($error as $key => $value) {
				if(false == $value)$this->errors->set_error_message($key);
			}
            return false;
        }
        return true;
    }
    /**
     * tacks on the end of the array
     * @param string path to the cache file
     * @return bool
     * */
    public function add_tail($path)
    {
        $error = @file_put_contents($path,');',FILE_APPEND);
        if(false === $error){
            $this->errors->set_error_message(__METHOD__.$this->cache_error);
            return false;
        }
        return true;
    }
    /**
     * operation to build themes (both admin or custom)
     * @return bool
     * */
    public function build_themes()
    {
        // -- init
		$error = array();
		
		$return = array();
        
		$build = array();
		// ./ init
		
        $theme_yml = self::get_cache_byfile('themes.yml.php');
        $app = self::get_cache_byfile('app.yml.php');
		
        $debugmode = General::is_set($app,'debugmode',false);
        if(true == $debugmode)$debugmode = true;
		
		$jquery = General::is_set($app,'jquery',false);
        $now = date('dis',strtotime('now'));

        // loop all theme types
        foreach($theme_yml as $type => $themes) {
			
            $build = array('js'=>'','css'=>'');
            // loop themes 
			foreach($themes as $tname => $theme) {
				
                // get path for current theme
                $current = str_replace(basename($theme['path']),'',$theme['path']);
        
				// if overide is set
                if(isset($theme['info']['overide']) AND trim($theme['info']['overide']) != '') {
                    $path = $current.$theme['overide']['js'];
                    if(true === $debugmode)
                        $path = $current.$theme['info']['overide']['js_working'];   
                }else{
					// get js scripts
                    $path = $current.'_/js';
                    if(true === $debugmode)
                        $path = $current.'_/components/js';
                }
				// loop through folders to get files
                $js = self::recurse_get_files($path,'.js');
				// if jquery ui is required by theme then get from main repo
				if(isset($theme['info']['jqueryui']))
					$js[] = $theme['info']['jqueryui'];
					// shift jquery to the front of the line
				array_unshift($js,$jquery);
		
                // get stylsheets
                $path = $current.'_/css';
                $css = self::recurse_get_files($path,'.css');
				if(isset($theme['info']['jqueryui-css'])) {
					foreach($theme['info']['jqueryui-css'] as $ui) {
						$css[] = $ui;
					}
				}
		
    
    // IF DEBUGMODE
                if(true === $debugmode) {
                    // gather and build scripts
                    $build['js'] .= "<!-- ".$theme['info']['name']."-->\n";
                    foreach($js as $j) {
						$build['js'] .= '<script src="'.WEBROOT.'/cms/scripts/js/'.str_replace(getcwd().'/','',$j).'"></script>'."\n";
                    }
                    // gather and build css
                    $build['css'] .= "<!-- ".$theme['info']['name']."-->\n";
                    foreach($css as $c) {
						$build['css'] .= '<link rel="stylesheet" href="'.WEBROOT.'/cms/scripts/css/'.str_replace(getcwd().'/','',$c).'"/>'."\n";
                    }
    /* ELSE */  }else{
                    // gather ,minify, then build scripts
                    $scr = '';
                    foreach($js as $j) {
                        $chk = file_get_contents($j);
                        if(false === $chk){
                            $error[] = true;
                        }else{
                            $scr.=$chk;
                        }
                    }
                    if('theme'==$type) {
                        $spath = '../../../upload/_/js/script.js';
                    }else{
                        $spath = '../../../_/js/script.js';
                    }
                    if(false !== @file_put_contents($current.$spath,$scr)) {
						if(defined('VERBOSE'))print General::message('notice',array('notice','verbose','added'),array(__METHOD__.'->'.__LINE__,$current.$spath));
					}
                    $build['js'] = '<script src="'.WEBROOT.'/cms/scripts/js/_/js/script.js'.'"></script>'."\n";
                    // gather ,minify, then build css
                    $scr = '';
                    foreach($css as $c) {
                        $chk = @file_get_contents($c);
                        if(false === $chk){
                            $error[] = true;
                        }else{
                            $scr.=$chk;
                        }
                    }
                    if('theme'==$type) {
                        $spath = '../../../upload/_/css/style.css';
                    }else{
                        $spath = '../../../_/css/style.css';
                    }
		    
                    if(false !== @file_put_contents($current.$spath,$scr)) {
			if(defined('VERBOSE'))print General::message('notice',array('notice','verbose','added'),array(__METHOD__.'->'.__LINE__,$current.$spath));
		    }
                    $build['css'] = '<link rel="stylesheet" href="'.WEBROOT.'/cms/scripts/css/_/css/style.css'.'?c='.$now.'"/>'."\n";
                }
                // render theme HTML file files
                $html = self::recurse_get_files($current,'.html.php');
				
                foreach($html as $name => $path) {
                    // render the template into a static HTML with bstwig 
					$rendered = addslashes($this->renderPhpToString($path,array('build'=>$build)));
					// if this is the install theme then the root /cms will always be the running location
					// so the script and css paths can be static
					if($name == 'install')$rendered = str_replace(WEBROOT.'/cms/scripts/css/',WEBROOT.'/cms/',$rendered);
					if($name == 'install')$rendered = str_replace(WEBROOT.'/cms/scripts/js/',WEBROOT.'/cms/',$rendered);
                    // if debugmode is false then compress
					if(false === $debugmode) {
                        $rendered = $this->compress($rendered);
                    }
                    $return[$type][$tname][basename($path)] = $rendered;
                }
            }
        }
        // check if errors
        if(in_array(false,$error)){
            $this->errors->set_error_message(__METHOD__.$this->cache_error);
            return false;
        }
        return $return;
    }
    
    
    // ---------------------------------- Public Static Functions
    
    /**
     * gets a cached file and returns its value
     * @param string file the file name ex: app.yml.php
     * @param string array key in question
     * @example to find $array['a']['b']['c'] use: recurse_array_get($array,array('a','b','c'));
     * @return array
     * */
    public static function get_cache_byfile($file,$key = false)
    {
        @include('cache/'.$file);
        if(false !== $key)return General::recurse_array_get($return,$key);
        return $return;
    }
    /**
	 * creates or updates YML config file
	 * @param $path string
	 * @param array YAML
	 * @return bool
	 * */
    public static function update_config($path,$content)
	{
		$yaml = Yaml::dump($content);
		$error = @file_put_contents($path,$yaml);
        if(false === $error){
			$f = str_replace(basename($path),'',$path);
            $this->errors->set_error_message(__METHOD__.$this_>config_error.$f);
            return false;
        }
        return true;
	}
    // ---------------------------------- Private Functions
    
    
    /**
     * recursively build a cache array
     * @param array $array
     * @return string
     * */
    private function recurse_built_array($array)
    {
        if(!is_array($array))return $array;
        $out = '';
        foreach ($array as $key => $val) {
                if('' == $val OR '' == $key)continue;
                if(is_array($val) || is_object($val)) {
                    $val = 'array('.$this->recurse_built_array($val).")";
                    $out .= "'".$key."'=>".$val.",";
                }else{
                    $out .= "'".$key."'=>'".$val."',";
                }
        }
        return $out;
    }
    /**
     * strip whitespace from php files
     * @param string $in
     * @return string
     * */
    private function compress($in)
    {
        $out = str_replace("\n",'',$in);
        $out = str_replace("\t",'',$out);
        $out = str_replace("\r",'',$out);
        $out = preg_replace('!\s+!', ' ', $out);
        $out = preg_replace('/<!--(.*)-->/Uis', '', $out);
        return $out;
    }
    /**
     * rander php to variable for compression
     * @param string {}
     * @return string
     * */
    private function renderPhpToString( )
    {
        if( is_array( func_get_arg(1) ) ) {
            extract( func_get_arg(1) );
        }
        ob_start();
        require func_get_arg( 0 );
        return ob_get_clean();
    }
}