# by default Gluon follows PSR-4 folder suggestions
# but you can specify another folder to attempt to autoload your own code
src_alt:
error_handler: gl_ErrorHandler
# if true then:
# infomration about include paths and other info will be rendered
# scripts will be rendered individually non-minified
# - if creating a theme using a pre-processor like Grunt ot Gulp then working files location needs to be specified (see documention)
# markup will not be compressed
debugmode: true 