class: \Gluon\Libraries\pdoDatabase
param:
    dsn: 'mysql:host=localhost;dbname=gl_db'
    username: gl_db
    password: abc1234
    encoding: utf8
    attributes: { DEFAULT_TABLE_TYPE: INNODB, DEFAULT_TABLE_CHARSET: utf8, DEFAULT_TABLE_COLLATE: utf8_general_ci }
