warning:
notice:
    success:
        uploaded: "[#0#] was saved successfully."
    theme_skipped:
        name: "Theme [#0#] [name] not set\nTheme skipped\n"
        type: "Theme [#0#] [type] not set\nTheme skipped\n"
        version: "Theme [#0#] version: [#1#] not compatible with current version: [#2#] --- Theme skipped\n"
error:
    upload:
        sizemax: "This file [#0#] has exceeded the allowed size limit. [#1#]"
        notallowed: "This file [#0#] type is not allowed. [#1#]"    
        movefile: "Failed to move file"
        upload: "File failed to upload"
        malicious: "File contains potential malicious content"