<?php
#auto-generated by Gluon\Libraries\Cache::__construct on 02/06/2017 16:40:31 America/Los_Angeles
$return = array('index.html.php'=>'<html>
    <head>
        <title>{# page.title #}</title>
<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />
<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">
<meta name=\"viewport\" content=\"width=device-width\">
<meta name=\"robots\" content=\"NOINDEX,NOFOLLOW\" />
<!-- Default-->
<link rel=\"stylesheet\" href=\"/Gluon/cms/scripts/css/themes/default/_/css/style.css\"/>
    </head>
    <body>
        <!-- Default-->
<script src=\"/Gluon/cms/scripts/js/_/components/jquery/jquery-3.1.1.min.js\"></script>
<script src=\"/Gluon/cms/scripts/js/themes/default/_/components/js/script.js\"></script>
    </body>
</html>',);