<?php
#auto-generated by Gluon\Libraries\Cache::__construct on 01/22/2017 21:53:14 America/Los_Angeles
$return = array('index.html.php'=>'<html>
    <head>
        <title>{# page.title #}</title>
<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />
<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">
<meta name=\"viewport\" content=\"width=device-width\">
<meta name=\"robots\" content=\"NOINDEX,NOFOLLOW\" />
<!-- Default-->
<link rel=\"stylesheet\" href=\"themes/default/_/css/style.css?c=225315\"/>
    </head>
    <body>
        <!-- Default-->
<script src=\"_/components/jquery/jquery-3.1.1.min.js?c=225315\"></script>
<script src=\"themes/default/_/components/js/script.js?c=225315\"></script>
    </body>
</html>',);